In [1]:
import numpy as np

In [2]:
def step1():
    Fa = np.array([[15600, 7540 , 20140, 0.07074],[18760, 2750, 18610, 0.07220],[17610, 14630, 13480, 0.07690],[19170, 610, 18390, 0.07242]])
    C = 299792.458
    print(Fa[1,0])
    v1 = np.array([[2 * (Fa[1,0] - Fa[0,0])],[2 * (Fa[2,0] - Fa[0,0])],[2 * (Fa[3,0] - Fa[0,0])]])
    v2 = np.array([[2 * (Fa[1,1] - Fa[0,1])],[2 * (Fa[2,1] - Fa[0,1])],[2 * (Fa[3,1] - Fa[0,1])]])
    v3 = np.array([[2 * (Fa[1,2] - Fa[0,2])],[2 * (Fa[2,2] - Fa[0,2])],[2 * (Fa[3,2] - Fa[0,2])]])
    v4 = np.array([[2 * C**2 * (Fa[0,3] - Fa[1,3])],[2 * C**2 * (Fa[0,3] - Fa[2,3])],[2 * C**2 * (Fa[0,3] - Fa[3,3])]])
    v5 = np.array([[Fa[0,0]**2 - Fa[1,0]**2 + Fa[0,1]**2 - Fa[1,1]**2 + Fa[0,2]**2 - Fa[1,2]**2 + C**2 * (Fa[1,3]**2 - Fa[0,3]**2)],
                   [Fa[0,0]**2 - Fa[2,0]**2 + Fa[0,1]**2 - Fa[2,1]**2 + Fa[0,2]**2 - Fa[2,2]**2 + C**2 * (Fa[2,3]**2 - Fa[0,3]**2)],
                   [Fa[0,0]**2 - Fa[3,0]**2 + Fa[0,1]**2 - Fa[3,1]**2 + Fa[0,2]**2 - Fa[3,2]**2 + C**2 * (Fa[3,3]**2 - Fa[0,3]**2)]])
   
    print(np.concatenate((v1, v2, v3), axis = 1))
    print(np.linalg.det(np.concatenate((v1, v2, v3), axis = 1)))
   
    alpha1 = -1 * np.linalg.det(np.concatenate((v2, v3, v5), axis = 1)) / np.linalg.det(np.concatenate((v2, v3, v1), axis = 1))
    beta1 = -1 * np.linalg.det(np.concatenate((v2, v3, v4), axis = 1)) / np.linalg.det(np.concatenate((v2, v3, v1), axis = 1))
    alpha2 = -1 * np.linalg.det(np.concatenate((v1, v3, v5), axis = 1)) / np.linalg.det(np.concatenate((v1, v3, v2), axis = 1))
    beta2 = -1 * np.linalg.det(np.concatenate((v1, v3, v4), axis = 1)) / np.linalg.det(np.concatenate((v1, v3, v2), axis = 1))
    alpha3 = -1 * np.linalg.det(np.concatenate((v1, v2, v5), axis = 1)) / np.linalg.det(np.concatenate((v1, v2, v3), axis = 1))
    beta3 = -1 * np.linalg.det(np.concatenate((v1, v2, v4), axis = 1)) / np.linalg.det(np.concatenate((v1, v2, v3), axis = 1))
   
    q0 = alpha1**2 - 2 * Fa[0,0] * alpha1 + Fa[0,0]**2 + alpha2**2 - 2 * Fa[0,1] * alpha2 + Fa[0,1]**2 + alpha3**2 - 2 * Fa[0,2] * alpha3 + Fa[0,2]**2 - C**2 * Fa[0,3]**2
    q1 = 2 * alpha1 * beta1 - 2 * Fa[0,0] * beta1 + 2 * alpha2 * beta2 - 2 * Fa[0,1] * beta2 + 2 * alpha3 * beta3 - 2 * Fa[0,2] * beta3 + 2 * C**2 * Fa[0,3]
    q2 = beta1**2 + beta2**2 + beta3**3 - C**2
   
    sol1 = (-1 * q1 + np.sqrt(q1**2 - 4 * q0 * q2)) / (2 * q2)
    sol2 = (-1 * q1 - np.sqrt(q1**2 - 4 * q0 * q2)) / (2 * q2)
   
    print(sol1, sol2)

    x1 = alpha1 + beta1 * sol1
    x2 = alpha1 + beta1 * sol2
    y1 = alpha2 + beta2 * sol1
    y2 = alpha2 + beta2 * sol2
    z1 = alpha3 + beta3 * sol1
    z2 = alpha3 + beta3 * sol2
   
    print(x1, y1, z1, sol1)
    print(x2, y2, z2, sol2)

In [3]:
step1()

18760.0
[[  6320.  -9580.  -3060.]
 [  4020.  14180. -13320.]
 [  7140. -13860.  -3500.]]
-223811335999.99954
-0.0002764161744194026 0.00030204303451664323
-41.741266616842694 -18.613543239282414 6124.964758902979 -0.0002764161744194026
-41.73504865590884 -18.97431505630408 6076.49635180564 0.00030204303451664323
